### ISSUE TITLE
Resource Timing Integration checklist

### ISSUE THREAD

**Issue by annevk** [whatwg/fetch#1197]
As #1185 is getting longer I'm worried I will start to miss things. Making a list here of things to double check. This is mainly for myself, but @yoavweiss and @noamr are free to use it and add to it, of course. We can also use this issue to settle architecture questions.

- [x] Does it deal with `blob:` and `data:` URLs correctly?
- [x] Are fields correctly set for synthetic responses?
- [ ] How does the setup for `<iframe>` and other browsing context containers work?
- [x] Have you done an editorial pass on "recording connnection timing info"?

**Comment by noamr** [comment]
Some details:

- For `blob:` & `data:` there shouldn't be ResourceTiming entries. I will make it more explicit in fetch
- "Recording connection 

> As #1185 is getting longer I'm worried I will start to miss things. Making a list here of things to double check. This is mainly for myself, but @yoavweiss and @noamr are free to use it and add to it, of course. We can also use this issue to settle architecture questions.
> 
> * [ ]  Does it deal with `blob:` and `data:` URLs correctly?
There should be no RT entries for `blob:` and `data:`. I will try to make it more explicit in `FETCH`.

> * [ ]  Are fields correctly set for synthetic responses?
Synthetic - you mean for cache/SW? I think they are right now, but yes we should double check.

> * [ ]  How does the setup for `<iframe>` and other browsing context containers work?
Need to look into the details - IFRAME should be reported as RT to the parent, and internally as NT.

> * [ ]  Have you done an editorial pass on "recording connnection timing info"?
@yoavweiss

**Comment by annevk** [comment]
Just to be extra clear, it doesn't matter how the service worker obtained the response, right? I.e., if the service worker used a `blob:` URL, you would get timings in the document, but not the service worker.

**Comment by noamr** [comment]
> Just to be extra clear, it doesn't matter how the service worker obtained the response, right? I.e., if the service worker used a `blob:` URL, you would get timings in the document, but not the service worker.

Right, the service worker returns a response that it has constructed in whatever way it wanted.

**Comment by annevk** [comment]
`<iframe>` will be sorted as part of updating `<iframe>`. I think this is all good now.
